### PR TITLE
Text Size Customization

### PR DESCRIPTION
**Pull request by MateoGarcia18**
Added a slider for text size configuration

### CODE REVIEW

**Comment by joshuaeduque** [comment]
Is this fully implemented? I see you doing something in MainActivity so I assume so.

**Comment by MateoGarcia18** [comment]
It should be fully implemented. I got it to apply the font size on all screens.

**Comment by MateoGarcia18** [comment]
I had that issue too. You have to uninstall the app and reinstall it to clear the old preferences that are incompatible with the new ones.

**Comment by joshuaeduque** [comment]
Ah alright, looks good then. In the future, can you make it so the text size gets reset when you use the clear preferences button in the settings page? I forgot to do it for the themes as well.

**Comment by MateoGarcia18** [comment]
I noticed that too. I was going to work on the clear preferences button next anyways.

**Pull request merged**
